// src/data/deals.ts

export const allDeals = [
  {
    id: "1",
    productId: "1",
    creatorId: "1",
    title: "Premium Arabica Coffee Beans - 1kg Pack",
    description:
      "Freshly roasted premium Arabica coffee beans from Coorg plantations. Direct from farmers to your cup.",
    targetCount: 25,
    currentCount: 18,
    pricePerItem: 899,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Koramangala, Bangalore",
    product: {
      id: "1",
      vendorId: "1",
      name: "Premium Arabica Coffee Beans",
      imageUrls: ["/images/coffee-beans.jpg"],
      basePrice: 1299,
      groupPrice: 899,
      inventoryCount: 100,
      minGroupSize: 15,
      maxGroupSize: 50,
      active: true,
      unit: "kg",
      tags: ["Organic", "Single Origin", "Medium Roast"],
      certifications: ["Organic India", "Fair Trade"],
      category: "Food & Beverages",
      vendor: {
        id: "1",
        userId: "1",
        businessName: "Coorg Coffee Co.",
        verified: true,
        rating: 4.8,
        totalOrders: 156,
      },
    },
  },
  {
    id: "2",
    productId: "2",
    creatorId: "2",
    title: "Artisan Sourdough Bread - Weekly Subscription",
    description:
      "Handcrafted sourdough bread made with traditional fermentation. Weekly home delivery in Bangalore.",
    targetCount: 20,
    currentCount: 12,
    pricePerItem: 180,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Indiranagar, Bangalore",
    product: {
      id: "2",
      vendorId: "2",
      name: "Artisan Sourdough Bread",
      imageUrls: ["/images/sourdough-bread.jpg"],
      basePrice: 250,
      groupPrice: 180,
      inventoryCount: 50,
      minGroupSize: 10,
      maxGroupSize: 30,
      active: true,
      unit: "loaf",
      tags: ["Handmade", "No Preservatives", "Whole Wheat"],
      certifications: ["FSSAI Certified"],
      category: "Food & Beverages",
      vendor: {
        id: "2",
        userId: "2",
        businessName: "Bangalore Bakehouse",
        verified: true,
        rating: 4.6,
        totalOrders: 89,
      },
    },
  },
  {
    id: "4",
    productId: "4",
    creatorId: "4",
    title: "Organic Mixed Vegetables Box - 5kg",
    description:
      "Fresh organic vegetables sourced directly from farms around Bangalore. Pesticide-free and nutritious.",
    targetCount: 40,
    currentCount: 28,
    pricePerItem: 350,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Whitefield, Bangalore",
    product: {
      id: "4",
      vendorId: "4",
      name: "Organic Mixed Vegetables",
      imageUrls: ["/images/organic-vegetables.jpg"],
      basePrice: 500,
      groupPrice: 350,
      inventoryCount: 100,
      minGroupSize: 25,
      maxGroupSize: 60,
      active: true,
      unit: "5kg box",
      tags: ["Organic", "Farm Fresh", "Pesticide Free"],
      certifications: ["Organic India", "FSSAI Certified"],
      category: "Food & Beverages",
      vendor: {
        id: "4",
        userId: "4",
        businessName: "Green Valley Farms",
        verified: true,
        rating: 4.7,
        totalOrders: 312,
      },
    },
  },
  {
    id: "5",
    productId: "5",
    creatorId: "5",
    title: "Handmade Natural Soap Set - 6 Bars",
    description:
      "Chemical-free handmade soaps with natural ingredients. Perfect for sensitive skin.",
    targetCount: 35,
    currentCount: 22,
    pricePerItem: 299,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Jayanagar, Bangalore",
    product: {
      id: "5",
      vendorId: "5",
      name: "Handmade Natural Soap Set",
      imageUrls: ["/images/handmade-soap.jpg"],
      basePrice: 450,
      groupPrice: 299,
      inventoryCount: 80,
      minGroupSize: 20,
      maxGroupSize: 50,
      active: true,
      unit: "6 bars",
      tags: ["Handmade", "Natural", "Chemical Free"],
      certifications: ["Ayush Certified"],
      category: "Health & Beauty",
      vendor: {
        id: "5",
        userId: "5",
        businessName: "Pure Essence",
        verified: true,
        rating: 4.5,
        totalOrders: 167,
      },
    },
  },
  {
    id: "6",
    productId: "6",
    creatorId: "6",
    title: "Authentic Garam Masala Blend - 250g",
    description:
      "Traditional garam masala blend made with premium spices. Freshly ground and aromatic.",
    targetCount: 50,
    currentCount: 35,
    pricePerItem: 180,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Malleshwaram, Bangalore",
    product: {
      id: "6",
      vendorId: "6",
      name: "Authentic Garam Masala Blend",
      imageUrls: ["/images/spice-mix.jpg"],
      basePrice: 280,
      groupPrice: 180,
      inventoryCount: 120,
      minGroupSize: 30,
      maxGroupSize: 80,
      active: true,
      unit: "250g pack",
      tags: ["Traditional", "Fresh Ground", "Premium"],
      certifications: ["FSSAI Certified", "Spices Board"],
      category: "Food & Beverages",
      vendor: {
        id: "6",
        userId: "6",
        businessName: "Spice Garden",
        verified: true,
        rating: 4.8,
        totalOrders: 445,
      },
    },
  },
  {
    id: "7",
    productId: "7",
    creatorId: "7",
    title: "Eco-Friendly Bamboo Toothbrush - Pack of 4",
    description:
      "Sustainable bamboo toothbrushes with biodegradable bristles. A greener choice for your daily oral care.",
    targetCount: 30,
    currentCount: 15,
    pricePerItem: 299,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Jayanagar, Bangalore",
    product: {
      id: "7",
      vendorId: "7",
      name: "Eco-Friendly Bamboo Toothbrush",
      imageUrls: ["/images/bamboo-toothbrush.jpg"],
      basePrice: 399,
      groupPrice: 299,
      inventoryCount: 200,
      minGroupSize: 15,
      maxGroupSize: 40,
      active: true,
      unit: "pack",
      tags: ["Eco-Friendly", "Biodegradable", "Sustainable"],
      certifications: ["Ayush Certified", "FSSAI Certified"],
      category: "Health & Beauty",
      vendor: {
        id: "7",
        userId: "7",
        businessName: "Green Solutions",
        verified: true,
        rating: 4.7,
        totalOrders: 210,
      },
    },
  },
  {
    id: "8",
    productId: "8",
    creatorId: "8",
    title: "Handcrafted Ceramic Planter",
    description:
      "Beautiful handmade ceramic planters for your home or garden. Perfect for succulents and small plants.",
    targetCount: 18,
    currentCount: 10,
    pricePerItem: 750,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Whitefield, Bangalore",
    product: {
      id: "8",
      vendorId: "8",
      name: "Handcrafted Ceramic Planter",
      imageUrls: ["/images/ceramic-planter.png"],
      basePrice: 950,
      groupPrice: 750,
      inventoryCount: 100,
      minGroupSize: 10,
      maxGroupSize: 25,
      active: true,
      unit: "piece",
      tags: ["Handmade", "Decor", "Ceramic"],
      certifications: [],
      category: "Home & Garden",
      vendor: {
        id: "8",
        userId: "8",
        businessName: "Crafts & Co.",
        verified: true,
        rating: 4.3,
        totalOrders: 112,
      },
    },
  },
  {
    id: "9",
    productId: "9",
    creatorId: "9",
    title: "Wireless Bluetooth Earbuds",
    description:
      "High-quality wireless Bluetooth earbuds with noise cancellation and long battery life.",
    targetCount: 60,
    currentCount: 35,
    pricePerItem: 1499,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Malleshwaram, Bangalore",
    product: {
      id: "9",
      vendorId: "9",
      name: "Wireless Bluetooth Earbuds",
      imageUrls: ["/images/bluetooth-earbuds.jpg"],
      basePrice: 1999,
      groupPrice: 1499,
      inventoryCount: 150,
      minGroupSize: 30,
      maxGroupSize: 100,
      active: true,
      unit: "pair",
      tags: ["Wireless", "Bluetooth", "Noise Cancellation"],
      certifications: ["CE Certified"],
      category: "Electronics",
      vendor: {
        id: "9",
        userId: "9",
        businessName: "Soundtech",
        verified: true,
        rating: 4.5,
        totalOrders: 580,
      },
    },
  },
  {
    id: "10",
    productId: "10",
    creatorId: "10",
    title: "Handwoven Pashmina Shawl from Kashmir",
    description:
      "Experience the luxurious warmth of an authentic handwoven Pashmina shawl, sourced directly from artisans in Kashmir.",
    targetCount: 15,
    currentCount: 8,
    pricePerItem: 2499,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "HSR Layout, Bangalore",
    product: {
      id: "10",
      vendorId: "10",
      name: "Handwoven Pashmina Shawl",
      imageUrls: ["/images/pashmina-shawl.jpg"],
      basePrice: 3999,
      groupPrice: 2499,
      inventoryCount: 30,
      minGroupSize: 10,
      maxGroupSize: 25,
      active: true,
      unit: "piece",
      tags: ["Handmade", "Luxury", "Pure Pashmina"],
      certifications: ["Geographical Indication (GI) Tag"],
      category: "Apparel & Accessories",
      vendor: {
        id: "10",
        userId: "10",
        businessName: "Kashmiri Weavers Collective",
        verified: true,
        rating: 4.9,
        totalOrders: 95,
      },
    },
  },
  {
    id: "11",
    productId: "11",
    creatorId: "11",
    title: "Terracotta Planter Set - Set of 3",
    description:
      "Handcrafted terracotta planters from rural artisans. Eco-friendly and perfect for adding an earthy touch to your home.",
    targetCount: 40,
    currentCount: 31,
    pricePerItem: 599,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Electronic City, Bangalore",
    product: {
      id: "11",
      vendorId: "11",
      name: "Terracotta Planter Set",
      imageUrls: ["/images/terracotta-planters.jpg"],
      basePrice: 899,
      groupPrice: 599,
      inventoryCount: 100,
      minGroupSize: 25,
      maxGroupSize: 70,
      active: true,
      unit: "set of 3",
      tags: ["Eco-friendly", "Handmade", "Gardening"],
      certifications: [],
      category: "Home & Garden",
      vendor: {
        id: "11",
        userId: "11",
        businessName: "Mitti ke Rang",
        verified: true,
        rating: 4.6,
        totalOrders: 240,
      },
    },
  },
  {
    id: "12",
    productId: "12",
    creatorId: "12",
    title: "Traditional Ayurvedic Hair Oil - 200ml",
    description:
      "A potent blend of traditional herbs like Bhringraj and Amla to promote hair growth and reduce hair fall. Made with a classical Ayurvedic recipe.",
    targetCount: 50,
    currentCount: 42,
    pricePerItem: 349,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Rajajinagar, Bangalore",
    product: {
      id: "12",
      vendorId: "12",
      name: "Traditional Ayurvedic Hair Oil",
      imageUrls: ["/images/ayurvedic-oil.png"],
      basePrice: 499,
      groupPrice: 349,
      inventoryCount: 200,
      minGroupSize: 30,
      maxGroupSize: 100,
      active: true,
      unit: "200ml bottle",
      tags: ["Ayurvedic", "Natural", "Hair Care"],
      certifications: ["Ayush Certified"],
      category: "Health & Beauty",
      vendor: {
        id: "12",
        userId: "12",
        businessName: "Veda Wellness",
        verified: true,
        rating: 4.7,
        totalOrders: 510,
      },
    },
  },
  {
    id: "13",
    productId: "13",
    creatorId: "13",
    title: "Original Madhubani Folk Art Painting",
    description:
      "Authentic Madhubani painting on handmade paper, created by artists from the Mithila region. A vibrant piece of Indian folk art.",
    targetCount: 10,
    currentCount: 4,
    pricePerItem: 1199,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "JP Nagar, Bangalore",
    product: {
      id: "13",
      vendorId: "13",
      name: "Original Madhubani Folk Art Painting",
      imageUrls: ["/images/madhubani-painting.jpg"],
      basePrice: 1599,
      groupPrice: 1199,
      inventoryCount: 20,
      minGroupSize: 5,
      maxGroupSize: 15,
      active: true,
      unit: "painting",
      tags: ["Folk Art", "Handmade", "Wall Decor"],
      certifications: [],
      category: "Home & Garden",
      vendor: {
        id: "13",
        userId: "13",
        businessName: "Mithila Kalakriti",
        verified: false,
        rating: 4.8,
        totalOrders: 35,
      },
    },
  },
  {
    id: "14",
    productId: "14",
    creatorId: "14",
    title: "Mysore Sandalwood Incense Sticks - 250g Pack",
    description:
      "Premium hand-rolled incense sticks made with pure Mysore sandalwood oil. Creates a serene and aromatic atmosphere.",
    targetCount: 100,
    currentCount: 78,
    pricePerItem: 250,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active" as const,
    deliveryDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Basavanagudi, Bangalore",
    product: {
      id: "14",
      vendorId: "14",
      name: "Mysore Sandalwood Incense Sticks",
      imageUrls: ["/images/incense-sticks.jpg"],
      basePrice: 400,
      groupPrice: 250,
      inventoryCount: 300,
      minGroupSize: 50,
      maxGroupSize: 150,
      active: true,
      unit: "250g pack",
      tags: ["Aromatic", "Sandalwood", "Natural"],
      certifications: ["Geographical Indication (GI) Tag"],
      category: "Home & Garden",
      vendor: {
        id: "14",
        userId: "14",
        businessName: "Sugandha Mysore",
        verified: true,
        rating: 4.9,
        totalOrders: 850,
      },
    },
  },
];
