// src/data/deals.ts

// You can define a type for your deal objects for better type safety
// This is based on the 'mockDeal' structure you provided.
export type GroupOrder = {
  id: string;
  slug: string; // Added slug for URL routing
  productId: string;
  creatorId: string;
  title: string;
  description: string;
  targetCount: number;
  currentCount: number;
  pricePerItem: number;
  startDate: string;
  endDate: string;
  status: "active" | "completed" | "cancelled";
  deliveryDate: string;
  pickupLocation: string;
  shippingCost: number;
  product: {
    id: string;
    vendorId: string;
    name: string;
    imageUrls: string[];
    basePrice: number;
    groupPrice: number;
    inventoryCount: number;
    minGroupSize: number;
    maxGroupSize: number;
    active: boolean;
    unit: string;
    tags: string[];
    certifications: string[];
    category: string;
    nutritionInfo?: string;
    vendor: {
      id: string;
      userId: string;
      businessName: string;
      description?: string;
      verified: boolean;
      rating: number;
      totalOrders: number;
      gstNumber?: string;
      fssaiNumber?: string;
    };
  };
};

export const allDeals: GroupOrder[] = [
  {
    id: "1",
    slug: "premium-arabica-coffee-beans-1kg-pack",
    productId: "1",
    creatorId: "1",
    title: "Premium Arabica Coffee Beans - 1kg Pack",
    description:
      "Freshly roasted premium Arabica coffee beans from Coorg plantations. Direct from farmers to your cup. Each batch is roasted to perfection to bring out the unique flavors and aromas.",
    targetCount: 25,
    currentCount: 18,
    pricePerItem: 899,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Koramangala, Bangalore",
    shippingCost: 0,
    product: {
      id: "1",
      vendorId: "1",
      name: "Premium Arabica Coffee Beans",
      imageUrls: [
        "/images/coffee-beans.jpg",
        "/images/coffee.jpg",
        "/images/coffee1.png",
      ],
      basePrice: 1299,
      groupPrice: 899,
      inventoryCount: 100,
      minGroupSize: 15,
      maxGroupSize: 50,
      active: true,
      unit: "kg",
      tags: ["Organic", "Single Origin", "Medium Roast", "Fair Trade"],
      certifications: ["Organic India", "Fair Trade", "FSSAI Certified"],
      category: "Food & Beverages",
      nutritionInfo:
        "Rich in antioxidants, low acidity, caffeine content: 95mg per cup",
      vendor: {
        id: "1",
        userId: "1",
        businessName: "Coorg Coffee Co.",
        description:
          "Premium coffee roasters since 1995, sourcing directly from Coorg plantations.",
        verified: true,
        rating: 4.8,
        totalOrders: 156,
        gstNumber: "29ABCDE1234F1Z5",
        fssaiNumber: "12345678901234",
      },
    },
  },
  {
    id: "2",
    slug: "artisan-sourdough-bread-weekly-subscription",
    productId: "2",
    creatorId: "2",
    title: "Artisan Sourdough Bread - Weekly Subscription",
    description:
      "Handcrafted sourdough bread made with traditional fermentation. Made with organic whole wheat flour for a rich flavor and healthy gut.",
    targetCount: 20,
    currentCount: 12,
    pricePerItem: 180,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Indiranagar, Bangalore",
    shippingCost: 0,
    product: {
      id: "2",
      vendorId: "2",
      name: "Artisan Sourdough Bread",
      imageUrls: ["/images/sourdough-bread.jpg"],
      basePrice: 250,
      groupPrice: 180,
      inventoryCount: 50,
      minGroupSize: 10,
      maxGroupSize: 30,
      active: true,
      unit: "loaf",
      tags: ["Handmade", "No Preservatives", "Whole Wheat"],
      certifications: ["FSSAI Certified"],
      category: "Food & Beverages",
      nutritionInfo: "Calories: 180 per slice, Fiber: 4g, Protein: 6g",
      vendor: {
        id: "2",
        userId: "2",
        businessName: "Bangalore Bakehouse",
        description:
          "Local bakery specializing in artisanal breads and pastries.",
        verified: true,
        rating: 4.6,
        totalOrders: 89,
        fssaiNumber: "11223344556677",
      },
    },
  },
  {
    id: "4",
    slug: "organic-mixed-vegetables-box-5kg",
    productId: "4",
    creatorId: "4",
    title: "Organic Mixed Vegetables Box - 5kg",
    description:
      "Fresh organic vegetables sourced directly from farms around Bangalore. Pesticide-free, nutritious, and delivered within 24 hours of harvest.",
    targetCount: 40,
    currentCount: 28,
    pricePerItem: 350,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Whitefield, Bangalore",
    shippingCost: 25,
    product: {
      id: "4",
      vendorId: "4",
      name: "Organic Mixed Vegetables",
      imageUrls: ["/images/organic-vegetables.jpg"],
      basePrice: 500,
      groupPrice: 350,
      inventoryCount: 100,
      minGroupSize: 25,
      maxGroupSize: 60,
      active: true,
      unit: "5kg box",
      tags: ["Organic", "Farm Fresh", "Pesticide Free"],
      certifications: ["Organic India", "FSSAI Certified"],
      category: "Food & Beverages",
      vendor: {
        id: "4",
        userId: "4",
        businessName: "Green Valley Farms",
        description:
          "A collective of local farmers promoting sustainable and organic agriculture.",
        verified: true,
        rating: 4.7,
        totalOrders: 312,
        fssaiNumber: "99887766554433",
      },
    },
  },
  {
    id: "5",
    slug: "handmade-natural-soap-set-6-bars",
    productId: "5",
    creatorId: "5",
    title: "Handmade Natural Soap Set - 6 Bars",
    description:
      "Chemical-free handmade soaps with natural ingredients like shea butter, coconut oil, and essential oils. Perfect for sensitive skin.",
    targetCount: 35,
    currentCount: 22,
    pricePerItem: 299,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Jayanagar, Bangalore",
    shippingCost: 0,
    product: {
      id: "5",
      vendorId: "5",
      name: "Handmade Natural Soap Set",
      imageUrls: ["/images/handmade-soap.jpg"],
      basePrice: 450,
      groupPrice: 299,
      inventoryCount: 80,
      minGroupSize: 20,
      maxGroupSize: 50,
      active: true,
      unit: "6 bars",
      tags: ["Handmade", "Natural", "Chemical Free", "Vegan"],
      certifications: ["Ayush Certified"],
      category: "Health & Beauty",
      vendor: {
        id: "5",
        userId: "5",
        businessName: "Pure Essence",
        description: "Creating small-batch, all-natural skincare products.",
        verified: true,
        rating: 4.5,
        totalOrders: 167,
      },
    },
  },
  {
    id: "6",
    slug: "authentic-garam-masala-blend-250g",
    productId: "6",
    creatorId: "6",
    title: "Authentic Garam Masala Blend - 250g",
    description:
      "Traditional garam masala blend made with 15 premium spices. Freshly ground and aromatic, perfect for authentic Indian cuisine.",
    targetCount: 50,
    currentCount: 35,
    pricePerItem: 180,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Malleshwaram, Bangalore",
    shippingCost: 0,
    product: {
      id: "6",
      vendorId: "6",
      name: "Authentic Garam Masala Blend",
      imageUrls: ["/images/spice-mix.jpg"],
      basePrice: 280,
      groupPrice: 180,
      inventoryCount: 120,
      minGroupSize: 30,
      maxGroupSize: 80,
      active: true,
      unit: "250g pack",
      tags: ["Traditional", "Fresh Ground", "Premium"],
      certifications: ["FSSAI Certified", "Spices Board"],
      category: "Food & Beverages",
      vendor: {
        id: "6",
        userId: "6",
        businessName: "Spice Garden",
        description:
          "Family-run business preserving traditional spice recipes for over 50 years.",
        verified: true,
        rating: 4.8,
        totalOrders: 445,
        fssaiNumber: "55667788990011",
      },
    },
  },
  {
    id: "7",
    slug: "eco-friendly-bamboo-toothbrush-pack-of-4",
    productId: "7",
    creatorId: "7",
    title: "Eco-Friendly Bamboo Toothbrush - Pack of 4",
    description:
      "Sustainable bamboo toothbrushes with biodegradable bristles. A greener choice for your daily oral care, featuring an ergonomic handle and BPA-free bristles.",
    targetCount: 30,
    currentCount: 15,
    pricePerItem: 299,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Jayanagar, Bangalore",
    shippingCost: 0,
    product: {
      id: "7",
      vendorId: "7",
      name: "Eco-Friendly Bamboo Toothbrush",
      imageUrls: ["/images/bamboo-toothbrush.png"],
      basePrice: 399,
      groupPrice: 299,
      inventoryCount: 200,
      minGroupSize: 15,
      maxGroupSize: 40,
      active: true,
      unit: "pack",
      tags: ["Eco-Friendly", "Biodegradable", "Sustainable"],
      certifications: ["Ayush Certified", "FSSAI Certified"],
      category: "Health & Beauty",
      vendor: {
        id: "7",
        userId: "7",
        businessName: "Green Solutions",
        description:
          "Providers of sustainable alternatives for everyday products.",
        verified: true,
        rating: 4.7,
        totalOrders: 210,
      },
    },
  },
  {
    id: "8",
    slug: "handcrafted-ceramic-planter",
    productId: "8",
    creatorId: "8",
    title: "Handcrafted Ceramic Planter",
    description:
      "Beautiful handmade ceramic planters for your home or garden. Each piece is unique and glazed with non-toxic colors.",
    targetCount: 18,
    currentCount: 10,
    pricePerItem: 750,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Whitefield, Bangalore",
    shippingCost: 50,
    product: {
      id: "8",
      vendorId: "8",
      name: "Handcrafted Ceramic Planter",
      imageUrls: ["/images/ceramic-planter.png"],
      basePrice: 950,
      groupPrice: 750,
      inventoryCount: 100,
      minGroupSize: 10,
      maxGroupSize: 25,
      active: true,
      unit: "piece",
      tags: ["Handmade", "Decor", "Ceramic"],
      certifications: [],
      category: "Home & Garden",
      vendor: {
        id: "8",
        userId: "8",
        businessName: "Crafts & Co.",
        description: "Studio for modern handmade ceramics and home decor.",
        verified: true,
        rating: 4.3,
        totalOrders: 112,
      },
    },
  },
  {
    id: "9",
    slug: "wireless-bluetooth-earbuds",
    productId: "9",
    creatorId: "9",
    title: "Wireless Bluetooth Earbuds",
    description:
      "High-quality wireless Bluetooth 5.2 earbuds with active noise cancellation, 30-hour battery life, and a compact charging case.",
    targetCount: 60,
    currentCount: 35,
    pricePerItem: 1499,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Malleshwaram, Bangalore",
    shippingCost: 0,
    product: {
      id: "9",
      vendorId: "9",
      name: "Wireless Bluetooth Earbuds",
      imageUrls: ["/images/bluetooth-earbuds.png"],
      basePrice: 1999,
      groupPrice: 1499,
      inventoryCount: 150,
      minGroupSize: 30,
      maxGroupSize: 100,
      active: true,
      unit: "pair",
      tags: ["Wireless", "Bluetooth", "Noise Cancellation", "Audio"],
      certifications: ["CE Certified"],
      category: "Electronics",
      vendor: {
        id: "9",
        userId: "9",
        businessName: "Soundtech",
        description:
          "Indian brand focused on affordable, high-quality audio electronics.",
        verified: true,
        rating: 4.5,
        totalOrders: 580,
      },
    },
  },
  {
    id: "10",
    slug: "handwoven-pashmina-shawl-from-kashmir",
    productId: "10",
    creatorId: "10",
    title: "Handwoven Pashmina Shawl from Kashmir",
    description:
      "Experience the luxurious warmth of an authentic handwoven Pashmina shawl, sourced directly from artisans in Kashmir.",
    targetCount: 15,
    currentCount: 8,
    pricePerItem: 2499,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "HSR Layout, Bangalore",
    shippingCost: 0,
    product: {
      id: "10",
      vendorId: "10",
      name: "Handwoven Pashmina Shawl",
      imageUrls: ["/images/pashmina-shawl.png"],
      basePrice: 3999,
      groupPrice: 2499,
      inventoryCount: 30,
      minGroupSize: 10,
      maxGroupSize: 25,
      active: true,
      unit: "piece",
      tags: ["Handmade", "Luxury", "Pure Pashmina"],
      certifications: ["Geographical Indication (GI) Tag"],
      category: "Apparel & Accessories",
      vendor: {
        id: "10",
        userId: "10",
        businessName: "Kashmiri Weavers Collective",
        description:
          "A collective empowering traditional weavers from the Kashmir valley.",
        verified: true,
        rating: 4.9,
        totalOrders: 95,
      },
    },
  },
  {
    id: "11",
    slug: "terracotta-planter-set-of-3",
    productId: "11",
    creatorId: "11",
    title: "Terracotta Planter Set - Set of 3",
    description:
      "Handcrafted terracotta planters from rural artisans. Eco-friendly and perfect for adding an earthy touch to your home.",
    targetCount: 40,
    currentCount: 31,
    pricePerItem: 599,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Electronic City, Bangalore",
    shippingCost: 75,
    product: {
      id: "11",
      vendorId: "11",
      name: "Terracotta Planter Set",
      imageUrls: ["/images/terracotta-planters.png"],
      basePrice: 899,
      groupPrice: 599,
      inventoryCount: 100,
      minGroupSize: 25,
      maxGroupSize: 70,
      active: true,
      unit: "set of 3",
      tags: ["Eco-friendly", "Handmade", "Gardening"],
      certifications: [],
      category: "Home & Garden",
      vendor: {
        id: "11",
        userId: "11",
        businessName: "Mitti ke Rang",
        description:
          "Supporting local potters and bringing traditional crafts to modern homes.",
        verified: true,
        rating: 4.6,
        totalOrders: 240,
      },
    },
  },
  {
    id: "12",
    slug: "traditional-ayurvedic-hair-oil-200ml",
    productId: "12",
    creatorId: "12",
    title: "Traditional Ayurvedic Hair Oil - 200ml",
    description:
      "A potent blend of traditional herbs like Bhringraj and Amla to promote hair growth and reduce hair fall. Made with a classical Ayurvedic recipe.",
    targetCount: 50,
    currentCount: 42,
    pricePerItem: 349,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Rajajinagar, Bangalore",
    shippingCost: 0,
    product: {
      id: "12",
      vendorId: "12",
      name: "Traditional Ayurvedic Hair Oil",
      imageUrls: ["/images/ayurvedic-oil.png"],
      basePrice: 499,
      groupPrice: 349,
      inventoryCount: 200,
      minGroupSize: 30,
      maxGroupSize: 100,
      active: true,
      unit: "200ml bottle",
      tags: ["Ayurvedic", "Natural", "Hair Care"],
      certifications: ["Ayush Certified"],
      category: "Health & Beauty",
      vendor: {
        id: "12",
        userId: "12",
        businessName: "Veda Wellness",
        description: "Authentic Ayurvedic formulations for modern wellness.",
        verified: true,
        rating: 4.7,
        totalOrders: 510,
      },
    },
  },
  {
    id: "13",
    slug: "original-madhubani-folk-art-painting",
    productId: "13",
    creatorId: "13",
    title: "Original Madhubani Folk Art Painting",
    description:
      "Authentic Madhubani painting on handmade paper, created by artists from the Mithila region. A vibrant piece of Indian folk art.",
    targetCount: 10,
    currentCount: 4,
    pricePerItem: 1199,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "JP Nagar, Bangalore",
    shippingCost: 100,
    product: {
      id: "13",
      vendorId: "13",
      name: "Original Madhubani Folk Art Painting",
      imageUrls: ["/images/madhubani-painting.jpg"],
      basePrice: 1599,
      groupPrice: 1199,
      inventoryCount: 20,
      minGroupSize: 5,
      maxGroupSize: 15,
      active: true,
      unit: "painting",
      tags: ["Folk Art", "Handmade", "Wall Decor"],
      certifications: [],
      category: "Home & Garden",
      vendor: {
        id: "13",
        userId: "13",
        businessName: "Mithila Kalakriti",
        description: "A social enterprise promoting Madhubani artists.",
        verified: false,
        rating: 4.8,
        totalOrders: 35,
      },
    },
  },
  {
    id: "14",
    slug: "mysore-sandalwood-incense-sticks-250g-pack",
    productId: "14",
    creatorId: "14",
    title: "Mysore Sandalwood Incense Sticks - 250g Pack",
    description:
      "Premium hand-rolled incense sticks made with pure Mysore sandalwood oil. Creates a serene and aromatic atmosphere for meditation and relaxation.",
    targetCount: 100,
    currentCount: 78,
    pricePerItem: 250,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    deliveryDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    pickupLocation: "Basavanagudi, Bangalore",
    shippingCost: 0,
    product: {
      id: "14",
      vendorId: "14",
      name: "Mysore Sandalwood Incense Sticks",
      imageUrls: ["/images/incense-sticks.png"],
      basePrice: 400,
      groupPrice: 250,
      inventoryCount: 300,
      minGroupSize: 50,
      maxGroupSize: 150,
      active: true,
      unit: "250g pack",
      tags: ["Aromatic", "Sandalwood", "Natural"],
      certifications: ["Geographical Indication (GI) Tag"],
      category: "Home & Garden",
      vendor: {
        id: "14",
        userId: "14",
        businessName: "Sugandha Mysore",
        description:
          "Official purveyors of authentic Mysore Sandalwood products.",
        verified: true,
        rating: 4.9,
        totalOrders: 850,
      },
    },
  },
];
